name = (input("send your name "))
surname = (input("send your surname "))
age = (input("age "))
email = (input("send email "))
location = (input("location "))
list = []
list.append(name)
list.append(surname)
list.append(age)
list.append(email)
list.append(location)
print(list)
